### ISSUE TITLE
Better format than xml for pml files?

### ISSUE THREAD

**Issue by FredrikNoren** [pxlp/pixelport#112]
Tried so far:

xml (current)
```xml
<Pml>
  <Scene
    camera="mul [
      projection { aspect: div [@root.screen_width, @root.screen_height] },
      lookat { eye: vec3 { x: 4, y: 4, z: 3 }, center: vec3 { x: 0, y: 0, z: 1 } }
    ]"
    pipeline="basic_pipeline { camera: @this.camera }"
    >
    <Box
      mesh="box_mesh {}"
      textures="textures { diffuse: texture_unit { texture: fill_texture { color: color { g: 1 } } } }"
      />
  </Scene>
</Pml>
```

json
```JSON
[
  {
    "type_name": "Pml",
    "children": [
      {
        "type_name": "Scene",
        "camera": "mul [
          projection { aspect: div [@root.screen_width, @root.screen_height] },
          lookat { eye: vec3 { x: 4, y: 4, z: 3 }, center: vec3 { x: 0, y: 0, z: 1 } }
        ]",
        "pipeline": "basic_pipeline { camera: @this.camera }",
        "children": [
          {
            "type_name": "Box",
            "mesh": "box_mesh {}",
            "textures": "textures { diffuse: texture_unit { texture: fill_texture { color: color { g: 1 } } } }"
          }
        ]
      }
    ]
  }
]
```

yaml
```yaml
Pml:
  children:
    - Scene:
        camera: |
          mul [
            projection { aspect: div [@root.screen_width, @root.screen_height] },
            lookat { eye: vec3 { x: 4, y: 4, z: 3 }, center: vec3 { x: 0, y: 0, z: 1 } }
          ]
        pipeline: basic_pipeline { camera: @this.camera }
        children:
          - Box:
              mesh: box_mesh {}
              textures: textures { diffuse: texture_unit { texture: fill_texture { color: color { g: 1 } } } }
```

custom yaml inspired format
```yaml
Pml
  Scene
    camera: mul [
              projection { aspect: div [@root.screen_width, @root.screen_height] },
              lookat { eye: vec3 { x: 4, y: 4, z: 3 }, center: vec3 { x: 0, y: 0, z: 1 } }
            ]
    pipeline: basic_pipeline { camera: @this.camera }
    Box
      mesh: box_mesh {}
      textures: textures { diffuse: texture_unit { texture: fill_texture { color: color { g: 1 } } } }
```
